import assert from 'node:assert/strict';
const {setWorkspace}=await import('./js/common.js');
const {initRuns,buildReplayRunButton,buildResumeRunButton}=await import('./js/runs.js');
const tick=()=>new Promise(resolve=>setTimeout(resolve,0));
const flush=async()=>{for(let i=0;i<5;i++)await tick();};
const response=(payload,status=200)=>({ok:status===200,status,json:async()=>payload,text:async()=>JSON.stringify(payload)});
const navigations=[];
let refreshes=0;
let finishWrite;
const writes=[];
globalThis.fetch=async(path)=>{writes.push(new URL(path,'http://dashboard.test'));return new Promise(resolve=>{finishWrite=resolve;});};
window.confirm=()=>true;
initRuns({navigateToRun:(id,workspace)=>navigations.push({id,workspace}),fetchAndRenderRuns:()=>{refreshes++;return Promise.resolve();}});
const body=document.getElementById('runs-body');
const run={run_id:'jrun-source',state:'failed',job_id:'fixture'};
setWorkspace('A');
const replay=buildReplayRunButton(run,body);
replay.dispatch('click');
replay.dispatch('click');
assert.equal(writes.length,1,'replay stays single flight');
assert.equal(buildReplayRunButton(run,body).disabled,true,'a refreshed replay control stays disabled');
assert.equal(writes[0].searchParams.get('workspace'),'A');
setWorkspace('B');
finishWrite(response({run_id:'jrun-replayed'}));
await flush();
assert.deepEqual(navigations,[],'a late replay result must not navigate B to A run');
assert.equal(refreshes,0);

setWorkspace('A');
const resume=buildResumeRunButton(run,body);
resume.dispatch('click');
assert.equal(writes.at(-1).searchParams.get('workspace'),'A');
setWorkspace('B');
finishWrite(response({error:'A resume refused'},409));
await flush();
assert.ok(!body.textContent.includes('A resume refused'),'a stale resume failure is not an error in B');
assert.equal(refreshes,0);

setWorkspace('A');
buildResumeRunButton(run,body).dispatch('click');
setWorkspace('B');
finishWrite(response({run_id:'jrun-resumed'}));
await flush();
assert.equal(refreshes,0,'a stale resume success never refreshes B');
assert.deepEqual(navigations,[]);
