[package]
name = "orbit-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.orbit]
stability = "internal"

[lints]
workspace = true

[dependencies]
orbit-common = { path = "../orbit-common" }
orbit-types = { path = "../orbit-types" }
chrono = { workspace = true }
chrono-tz.workspace = true
serde = { workspace = true }
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
