[package]
name = "orbit-search"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.orbit]
stability = "internal"

[lints]
workspace = true

[dependencies]
orbit-common = { path = "../orbit-common", features = ["sqlite"] }
orbit-types = { path = "../orbit-types" }
rusqlite.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
